################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

   - &PccH

      Name: PccH

      # ID to load the MSP definition as
      ID: PccHMSP

      # MSPDir is the filesystem path which contains the MSP configuration
      MSPDir: ../../../../artifacts/crypto-config/PccHMSP/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('PccHMSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('PccHMSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('PccHMSP.admin')"

      # OrdererEndpoints is a list of all orderers this org runs which clients
      # and peers may to connect to to push transactions and receive blocks respectively.
      OrdererEndpoints:
         - orderer0.cbody.com:7050
         - orderer1.cbody.com:7150
         - orderer2.cbody.com:7250
         - orderer3.cbody.com:7350
         - orderer4.cbody.com:7450

      AnchorPeers:
         # AnchorPeers defines the location of peers which can be used
         # for cross org gossip communication.  Note, this value is only
         # encoded in the genesis block in the Application section context
         - Host: peer0.pcch.net
           Port: 7051
   - &WakandaGov

      Name: WakandaGov

      # ID to load the MSP definition as
      ID: WakandaGovMSP

      # MSPDir is the filesystem path which contains the MSP configuration
      MSPDir: ../../../../artifacts/crypto-config/WakandaGovMSP/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('WakandaGovMSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('WakandaGovMSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('WakandaGovMSP.admin')"

      # OrdererEndpoints is a list of all orderers this org runs which clients
      # and peers may to connect to to push transactions and receive blocks respectively.
      OrdererEndpoints:
         - orderer0.cbody.com:7050
         - orderer1.cbody.com:7150
         - orderer2.cbody.com:7250
         - orderer3.cbody.com:7350
         - orderer4.cbody.com:7450

      AnchorPeers:
         # AnchorPeers defines the location of peers which can be used
         # for cross org gossip communication.  Note, this value is only
         # encoded in the genesis block in the Application section context
         - Host: peer0.gov.wakanda
           Port: 7251
