version: '2'

networks:
    myplatform:

services:

    cli.rebel.inc:
        extends:
            file: nodebase.yaml
            service: cli
        container_name: cli.rebel.inc
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - CORE_PEER_ID=cli.rebel.inc
            - CORE_PEER_ADDRESS=peer1.rebel.inc:7451
            - CORE_PEER_LOCALMSPID=RebelMSP
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/RebelMSP/peer1.rebel.inc/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/RebelMSP/peer1.rebel.inc/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/rebel.inc
        command: sh
        volumes:
            - ../../../../artifacts:/var/artifacts
            - ../scripts/container:/setup
            - ../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
