version: '2'

networks:
    myplatform:

services:

    peer1.rebel.inc:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer1.rebel.inc
        environment:
            - CORE_PEER_ID=peer1.rebel.inc
            - CORE_PEER_ADDRESS=peer1.rebel.inc:7451
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7451
            - CORE_PEER_LOCALMSPID=RebelMSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/RebelMSP/peer1.rebel.inc/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/RebelMSP/peer1.rebel.inc/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/RebelMSP/peer1.rebel.inc/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/RebelMSP/peer1.rebel.inc/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.rebel.inc:7551
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.rebel.inc:7451
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7452
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/RebelMSP/peer1.rebel.inc
        volumes:
            - /var/run:/host/var/run
            - ../../../../artifacts/production/RebelMSP/peer1.rebel.inc:/var/artifacts/production
            - ../../../../artifacts/crypto-config/RebelMSP/peer1.rebel.inc:/var/artifacts/crypto-config/RebelMSP/peer1.rebel.inc
        ports:
            - 7451:7451
            - 7453:7453
