################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

   - &CBody
      Name: CBody
      ID: CBodyMSP
      MSPDir: /var/artifacts/crypto-config/CBodyMSP/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('CBodyMSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('CBodyMSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('CBodyMSP.admin')"

   - &PccH
      Name: PccH
      ID: PccHMSP
      MSPDir: /var/artifacts/crypto-config/PccHMSP/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('PccHMSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('PccHMSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('PccHMSP.admin')"

      OrdererEndpoints:
         - orderer0.cbody.com:7050
         - orderer1.cbody.com:7150
         - orderer2.cbody.com:7250
         - orderer3.cbody.com:7350
         - orderer4.cbody.com:7450

      AnchorPeers:
         - Host: peer0.pcch.net
           Port: 7051

   - &WakandaGov
      Name: WakandaGov
      ID: WakandaGovMSP
      MSPDir: /var/artifacts/crypto-config/WakandaGovMSP/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('WakandaGovMSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('WakandaGovMSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('WakandaGovMSP.admin')"

      OrdererEndpoints:
         - orderer0.cbody.com:7050
         - orderer1.cbody.com:7150
         - orderer2.cbody.com:7250
         - orderer3.cbody.com:7350
         - orderer4.cbody.com:7450

      AnchorPeers:
         - Host: peer0.gov.wakanda
           Port: 7251

Capabilities:
   Channel: &ChannelCapabilities
      V1_4_3: true
      V1_3: false
      V1_1: false
   Orderer: &OrdererCapabilities
      V1_4_2: true
      V1_1: false
   Application: &ApplicationCapabilities
      V1_4_2: true
      V1_3: false
      V1_2: false
      V1_1: false

################################################################################
#
#   SECTION: Application
#
#   This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

   # Organizations is the list of orgs which are defined as participants on
   # the application side of the network
   Organizations:
   Policies:
      Readers:
         Type: ImplicitMeta
         Rule: "ANY Readers"
      Writers:
         Type: ImplicitMeta
         Rule: "ANY Writers"
      Admins:
         Type: ImplicitMeta
         Rule: "MAJORITY Admins"

   Capabilities:
      <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

   OrdererType: etcdraft
   Addresses:
      - orderer0.cbody.com:7050
      - orderer1.cbody.com:7150
      - orderer2.cbody.com:7250
      - orderer3.cbody.com:7350
      - orderer4.cbody.com:7450
   BatchTimeout: 2s
   BatchSize:
      MaxMessageCount: 500
      AbsoluteMaxBytes: 99 MB
      PreferredMaxBytes: 2 MB
   MaxChannels: 10
   EtcdRaft:
      Consenters:
         - Host: orderer0.cbody.com
           Port: 7050
           ClientTLSCert: /var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com/tls-msp/signcerts/cert.pem
           ServerTLSCert: /var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com/tls-msp/signcerts/cert.pem
         - Host: orderer1.cbody.com
           Port: 7150
           ClientTLSCert: /var/artifacts/crypto-config/CBodyMSP/orderer1.cbody.com/tls-msp/signcerts/cert.pem
           ServerTLSCert: /var/artifacts/crypto-config/CBodyMSP/orderer1.cbody.com/tls-msp/signcerts/cert.pem
         - Host: orderer2.cbody.com
           Port: 7250
           ClientTLSCert: /var/artifacts/crypto-config/CBodyMSP/orderer2.cbody.com/tls-msp/signcerts/cert.pem
           ServerTLSCert: /var/artifacts/crypto-config/CBodyMSP/orderer2.cbody.com/tls-msp/signcerts/cert.pem
         - Host: orderer3.cbody.com
           Port: 7350
           ClientTLSCert: /var/artifacts/crypto-config/CBodyMSP/orderer3.cbody.com/tls-msp/signcerts/cert.pem
           ServerTLSCert: /var/artifacts/crypto-config/CBodyMSP/orderer3.cbody.com/tls-msp/signcerts/cert.pem
         - Host: orderer4.cbody.com
           Port: 7450
           ClientTLSCert: /var/artifacts/crypto-config/CBodyMSP/orderer4.cbody.com/tls-msp/signcerts/cert.pem
           ServerTLSCert: /var/artifacts/crypto-config/CBodyMSP/orderer4.cbody.com/tls-msp/signcerts/cert.pem

      Options:
         TickInterval: 500ms
         ElectionTick: 10
         HeartbeatTick: 1
         MaxInflightBlocks: 5
         SnapshotIntervalSize: 20 MB

   Organizations:
   Policies:
      Readers:
         Type: ImplicitMeta
         Rule: "ANY Readers"
      Writers:
         Type: ImplicitMeta
         Rule: "ANY Writers"
      Admins:
         Type: ImplicitMeta
         Rule: "MAJORITY Admins"
      BlockValidation:
         Type: ImplicitMeta
         Rule: "ANY Writers"

Channel: &ChannelDefaults
   Policies:
      Readers:
         Type: ImplicitMeta
         Rule: "ANY Readers"
      Writers:
         Type: ImplicitMeta
         Rule: "ANY Writers"
      Admins:
         Type: ImplicitMeta
         Rule: "MAJORITY Admins"

   Capabilities:
      <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
#   Different configuration profiles may be encoded here to be specified as
#   parameters to the configtxgen tool.
#
################################################################################
Profiles:

   OrgsOrdererGenesis:
      <<: *ChannelDefaults
      Orderer:
         <<: *OrdererDefaults
         Organizations:
            - *CBody
         Capabilities:
            <<: *OrdererCapabilities
      Consortiums:
         Big4HK:
            Organizations:
               - *PccH
               - *WakandaGov

   OrgsChannel:
      Consortium: Big4HK
      <<: *ChannelDefaults
      Application:
         <<: *ApplicationDefaults
         Organizations:
            - *PccH
            - *WakandaGov
         Capabilities:
            <<: *ApplicationCapabilities
