---
name: myproject_myplatform-all
version: 1.0.0

channels:
  genericchannel:
    orderers:
      - orderer0.cbody.com
    peers:
      peer0.pcch.net:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.pcch.net:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.gov.wakanda:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.gov.wakanda:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincodes:
      - eventstore:1.0

organizations:
  PccHMSP:
    mspid: PccHMSP
    peers:
      - peer0.pcch.net
      - peer1.pcch.net
    certificateAuthorities:
      - rca.pcch.net
    adminPrivateKey:
      path: /var/artifacts/crypto-config/PccHMSP/admin/msp/keystore/key.pem
    signedCert:
      path: /var/artifacts/crypto-config/PccHMSP/admin/msp/signcerts/cert.pem
  WakandaGovMSP:
    mspid: WakandaGovMSP
    peers:
      - peer0.gov.wakanda
      - peer1.gov.wakanda
    certificateAuthorities:
      - rca.gov.wakanda
    adminPrivateKey:
      path: /var/artifacts/crypto-config/WakandaGovMSP/admin/msp/keystore/key.pem
    signedCert:
      path: /var/artifacts/crypto-config/WakandaGovMSP/admin/msp/signcerts/cert.pem

orderers:
  orderer0.cbody.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer0.cbody.com
    #      grpc-max-send-message-length: 4000
    tlsCACerts:
      path: /var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem

peers:
  peer0.pcch.net:
    url: grpcs://localhost:7051
    eventUrl: grpcs://localhost:7053
    tlsCACerts:
      path: /var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer0.pcch.net
  peer1.pcch.net:
    url: grpcs://localhost:7151
    eventUrl: grpcs://localhost:7153
    tlsCACerts:
      path: /var/artifacts/crypto-config/PccHMSP/peer1.pcch.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer1.pcch.net
  peer0.gov.wakanda:
    url: grpcs://localhost:7251
    eventUrl: grpcs://localhost:7253
    tlsCACerts:
      path: /var/artifacts/crypto-config/WakandaGovMSP/peer0.gov.wakanda/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer0.gov.wakanda
  peer1.gov.wakanda:
    url: grpcs://localhost:7351
    eventUrl: grpcs://localhost:7353
    tlsCACerts:
      path: /var/artifacts/crypto-config/WakandaGovMSP/peer1.gov.wakanda/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer1.gov.wakanda

certificateAuthorities:
  rca.pcch.net:
    url: https://localhost:6054
    caName: rca.pcch.net
    tlsCACerts:
      path: /var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/assets/tls-ca/tls-ca-cert.pem
    registrar:
      - enrollId: rca-pcch-admin
        enrollSecret: rca-pcch-adminPW
    httpOptions:
      verify: false
  rca.gov.wakanda:
    url: https://localhost:6055
    caName: rca.gov.wakanda
    tlsCACerts:
      path: /var/artifacts/crypto-config/WakandaGovMSP/peer0.gov.wakanda/assets/tls-ca/tls-ca-cert.pem
    registrar:
      - enrollId: rca-wakanda-admin
        enrollSecret: rca-wakanda-adminPW
    httpOptions:
      verify: false
