version: '2'

networks:
    myplatform:

services:

    tls-ca.cbody.com:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: tls-ca.cbody.com
        restart: always
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - FABRIC_CA_SERVER_HOME=/var/artifacts/crypto-config/CBodyMSP/tls/server
            - FABRIC_CA_SERVER_CSR_CN=tls-ca.cbody.com
            - FABRIC_CA_SERVER_CA_NAME=tls-ca.cbody.com
        ports:
            - 6052:6052
        command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminPW --cfg.affiliations.allowremove --cfg.identities.allowremove --port 6052'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/var/artifacts

    rca.cbody.com:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: rca.cbody.com
        restart: always
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - FABRIC_CA_SERVER_HOME=/var/artifacts/crypto-config/CBodyMSP/ca/server
            - FABRIC_CA_SERVER_CSR_CN=rca.cbody.com
            - FABRIC_CA_SERVER_CA_NAME=rca.cbody.com
        ports:
            - 6053:6053
        command: sh -c 'fabric-ca-server start -d -b rca-hktfp-admin:rca-hktfp-adminPW --cfg.affiliations.allowremove --cfg.identities.allowremove --port 6053'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/var/artifacts

    rca.pcch.net:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: rca.pcch.net
        restart: always
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - FABRIC_CA_SERVER_HOME=/var/artifacts/crypto-config/PccHMSP/ca/server
            - FABRIC_CA_SERVER_CSR_CN=rca.pcch.net
            - FABRIC_CA_SERVER_CA_NAME=rca.pcch.net
        ports:
            - 6054:6054
        command: sh -c 'fabric-ca-server start -d -b rca-pcch-admin:rca-pcch-adminPW --cfg.affiliations.allowremove  --cfg.identities.allowremove --port 6054'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/var/artifacts

    rca.gov.hk:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: rca.gov.hk
        restart: always
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - FABRIC_CA_SERVER_HOME=/var/artifacts/crypto-config/HKGovMSP/ca/server
            - FABRIC_CA_SERVER_CSR_CN=rca.gov.hk
            - FABRIC_CA_SERVER_CA_NAME=rca.gov.hk
        ports:
            - 6055:6055
        command: sh -c 'fabric-ca-server start -d -b rca-hkgov-admin:rca-hkgov-adminPW --cfg.affiliations.allowremove  --cfg.identities.allowremove --port 6055'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/var/artifacts

    peer0.pcch.net:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer0.pcch.net
        environment:
            - CORE_PEER_ID=peer0.pcch.net
            - CORE_PEER_ADDRESS=peer0.pcch.net:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_LOCALMSPID=PccHMSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.pcch.net:7151
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pcch.net:7051
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/PccHMSP/peer0.pcch.net
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/PccHMSP/peer0.pcch.net:/var/artifacts/production
            - ../artifacts/crypto-config/PccHMSP/peer0.pcch.net:/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net
        ports:
            - 7051:7051
            - 7053:7053

    peer1.pcch.net:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer1.pcch.net
        environment:
            - CORE_PEER_ID=peer1.pcch.net
            - CORE_PEER_ADDRESS=peer1.pcch.net:7151
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7151
            - CORE_PEER_LOCALMSPID=PccHMSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/PccHMSP/peer1.pcch.net/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/PccHMSP/peer1.pcch.net/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/PccHMSP/peer1.pcch.net/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/PccHMSP/peer1.pcch.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pcch.net:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.pcch.net:7151
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7152
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/PccHMSP/peer1.pcch.net
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/PccHMSP/peer1.pcch.net:/var/artifacts/production
            - ../artifacts/crypto-config/PccHMSP/peer1.pcch.net:/var/artifacts/crypto-config/PccHMSP/peer1.pcch.net
        ports:
            - 7151:7151
            - 7153:7153

    peer0.gov.hk:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer0.gov.hk
        environment:
            - CORE_PEER_ID=peer0.gov.hk
            - CORE_PEER_ADDRESS=peer0.gov.hk:7251
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7251
            - CORE_PEER_LOCALMSPID=HKGovMSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/HKGovMSP/peer0.gov.hk/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/HKGovMSP/peer0.gov.hk/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/HKGovMSP/peer0.gov.hk/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/HKGovMSP/peer0.gov.hk/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.gov.hk:7351
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.gov.hk:7251
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7252
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/HKGovMSP/peer0.gov.hk
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/HKGovMSP/peer0.gov.hk:/var/artifacts/production
            - ../artifacts/crypto-config/HKGovMSP/peer0.gov.hk:/var/artifacts/crypto-config/HKGovMSP/peer0.gov.hk
        ports:
            - 7251:7251
            - 7253:7253

    peer1.gov.hk:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer1.gov.hk
        environment:
            - CORE_PEER_ID=peer1.gov.hk
            - CORE_PEER_ADDRESS=peer1.gov.hk:7351
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7351
            - CORE_PEER_LOCALMSPID=HKGovMSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/HKGovMSP/peer1.gov.hk/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/HKGovMSP/peer1.gov.hk/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/HKGovMSP/peer1.gov.hk/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/HKGovMSP/peer1.gov.hk/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.gov.hk:7251
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.gov.hk:7351
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7352
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/HKGovMSP/peer1.gov.hk
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/HKGovMSP/peer1.gov.hk:/var/artifacts/production
            - ../artifacts/crypto-config/HKGovMSP/peer1.gov.hk:/var/artifacts/crypto-config/HKGovMSP/peer1.gov.hk
        ports:
            - 7351:7351
            - 7353:7353

    orderer0.cbody.com:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer0.cbody.com
        environment:
            - ORDERER_HOST=orderer0.cbody.com
            - ORDERER_HOME=/var/artifacts/orderer
            - ORDERER_GENERAL_LOCALMSPID=CBodyMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_GENESISFILE=/var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_LISTENPORT=7050
        volumes:
            - ../artifacts/production/CBodyMSP/orderer0.cbody.com:/var/artifacts/production
            - ../artifacts/crypto-config/CBodyMSP/orderer0.cbody.com:/var/artifacts/crypto-config/CBodyMSP/orderer0.cbody.com
        ports:
            - 7050:7050

    orderer1.cbody.com:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer1.cbody.com
        environment:
            - ORDERER_HOST=orderer1.cbody.com
            - ORDERER_HOME=/var/artifacts/orderer
            - ORDERER_GENERAL_LOCALMSPID=CBodyMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/artifacts/crypto-config/CBodyMSP/orderer1.cbody.com/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/artifacts/crypto-config/CBodyMSP/orderer1.cbody.com/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/artifacts/crypto-config/CBodyMSP/orderer1.cbody.com/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/artifacts/crypto-config/CBodyMSP/orderer1.cbody.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_GENESISFILE=/var/artifacts/crypto-config/CBodyMSP/orderer1.cbody.com/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/artifacts/crypto-config/CBodyMSP/orderer1.cbody.com/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/artifacts/crypto-config/CBodyMSP/orderer1.cbody.com/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/artifacts/crypto-config/CBodyMSP/orderer1.cbody.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_LISTENPORT=7150
        volumes:
            - ../artifacts/production/CBodyMSP/orderer1.cbody.com:/var/artifacts/production
            - ../artifacts/crypto-config/CBodyMSP/orderer1.cbody.com:/var/artifacts/crypto-config/CBodyMSP/orderer1.cbody.com
        ports:
            - 7150:7150

    orderer2.cbody.com:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer2.cbody.com
        environment:
            - ORDERER_HOST=orderer2.cbody.com
            - ORDERER_HOME=/var/artifacts/orderer
            - ORDERER_GENERAL_LOCALMSPID=CBodyMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/artifacts/crypto-config/CBodyMSP/orderer2.cbody.com/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/artifacts/crypto-config/CBodyMSP/orderer2.cbody.com/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/artifacts/crypto-config/CBodyMSP/orderer2.cbody.com/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/artifacts/crypto-config/CBodyMSP/orderer2.cbody.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_GENESISFILE=/var/artifacts/crypto-config/CBodyMSP/orderer2.cbody.com/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/artifacts/crypto-config/CBodyMSP/orderer2.cbody.com/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/artifacts/crypto-config/CBodyMSP/orderer2.cbody.com/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/artifacts/crypto-config/CBodyMSP/orderer2.cbody.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_LISTENPORT=7250
        volumes:
            - ../artifacts/production/CBodyMSP/orderer2.cbody.com:/var/artifacts/production
            - ../artifacts/crypto-config/CBodyMSP/orderer2.cbody.com:/var/artifacts/crypto-config/CBodyMSP/orderer2.cbody.com
        ports:
            - 7250:7250

    orderer3.cbody.com:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer3.cbody.com
        environment:
            - ORDERER_HOST=orderer3.cbody.com
            - ORDERER_HOME=/var/artifacts/orderer
            - ORDERER_GENERAL_LOCALMSPID=CBodyMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/artifacts/crypto-config/CBodyMSP/orderer3.cbody.com/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/artifacts/crypto-config/CBodyMSP/orderer3.cbody.com/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/artifacts/crypto-config/CBodyMSP/orderer3.cbody.com/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/artifacts/crypto-config/CBodyMSP/orderer3.cbody.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_GENESISFILE=/var/artifacts/crypto-config/CBodyMSP/orderer3.cbody.com/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/artifacts/crypto-config/CBodyMSP/orderer3.cbody.com/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/artifacts/crypto-config/CBodyMSP/orderer3.cbody.com/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/artifacts/crypto-config/CBodyMSP/orderer3.cbody.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_LISTENPORT=7350
        volumes:
            - ../artifacts/production/CBodyMSP/orderer3.cbody.com:/var/artifacts/production
            - ../artifacts/crypto-config/CBodyMSP/orderer3.cbody.com:/var/artifacts/crypto-config/CBodyMSP/orderer3.cbody.com
        ports:
            - 7350:7350

    orderer4.cbody.com:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer4.cbody.com
        environment:
            - ORDERER_HOST=orderer4.cbody.com
            - ORDERER_HOME=/var/artifacts/orderer
            - ORDERER_GENERAL_LOCALMSPID=CBodyMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/artifacts/crypto-config/CBodyMSP/orderer4.cbody.com/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/artifacts/crypto-config/CBodyMSP/orderer4.cbody.com/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/artifacts/crypto-config/CBodyMSP/orderer4.cbody.com/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/artifacts/crypto-config/CBodyMSP/orderer4.cbody.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_GENESISFILE=/var/artifacts/crypto-config/CBodyMSP/orderer4.cbody.com/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/artifacts/crypto-config/CBodyMSP/orderer4.cbody.com/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/artifacts/crypto-config/CBodyMSP/orderer4.cbody.com/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/artifacts/crypto-config/CBodyMSP/orderer4.cbody.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_LISTENPORT=7450
        volumes:
            - ../artifacts/production/CBodyMSP/orderer4.cbody.com:/var/artifacts/production
            - ../artifacts/crypto-config/CBodyMSP/orderer4.cbody.com:/var/artifacts/crypto-config/CBodyMSP/orderer4.cbody.com
        ports:
            - 7450:7450

    cli.pcch.net:
        extends:
            file: nodebase.yaml
            service: cli
        container_name: cli.pcch.net
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - CORE_PEER_ID=cli.pcch.net
            - CORE_PEER_ADDRESS=peer0.pcch.net:7051
            - CORE_PEER_LOCALMSPID=PccHMSP
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/pcch.net
        command: sh
        volumes:
            - ../artifacts:/var/artifacts
            - ../scripts/container:/setup
            - ../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode

    cli.gov.hk:
        extends:
            file: nodebase.yaml
            service: cli
        container_name: cli.gov.hk
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - CORE_PEER_ID=cli.gov.hk
            - CORE_PEER_ADDRESS=peer0.gov.hk:7251
            - CORE_PEER_LOCALMSPID=HKGovMSP
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/HKGovMSP/peer0.gov.hk/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/HKGovMSP/peer0.gov.hk/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/gov.hk
        command: sh
        volumes:
            - ../artifacts:/var/artifacts
            - ../scripts/container:/setup
            - ../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode

    cadvisor:
        container_name: cadvisor
        image: google/cadvisor
        restart: always
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        ports:
            - 8080:8080
