version: '2'

networks:
    myplatform:

services:

    peer0.pcch.net:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer0.pcch.net
        restart: unless-stopped
        environment:
            - CORE_PEER_ID=peer0.pcch.net
            - CORE_PEER_ADDRESS=peer0.pcch.net:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_LOCALMSPID=PccHMSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.pcch.net:7151
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pcch.net:7051
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/PccHMSP/peer0.pcch.net
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/PccHMSP/peer0.pcch.net:/var/artifacts/production
            - ../artifacts/crypto-config/PccHMSP/peer0.pcch.net:/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net
        ports:
            - 7051:7051
            - 7053:7053

    peer1.pcch.net:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer1.pcch.net
        restart: unless-stopped
        environment:
            - CORE_PEER_ID=peer1.pcch.net
            - CORE_PEER_ADDRESS=peer1.pcch.net:7151
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7151
            - CORE_PEER_LOCALMSPID=PccHMSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/PccHMSP/peer1.pcch.net/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/PccHMSP/peer1.pcch.net/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/PccHMSP/peer1.pcch.net/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/PccHMSP/peer1.pcch.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pcch.net:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.pcch.net:7151
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7152
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/PccHMSP/peer1.pcch.net
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/PccHMSP/peer1.pcch.net:/var/artifacts/production
            - ../artifacts/crypto-config/PccHMSP/peer1.pcch.net:/var/artifacts/crypto-config/PccHMSP/peer1.pcch.net
        ports:
            - 7151:7151
            - 7153:7153

    peer0.gov.wakanda:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer0.gov.wakanda
        restart: unless-stopped
        environment:
            - CORE_PEER_ID=peer0.gov.wakanda
            - CORE_PEER_ADDRESS=peer0.gov.wakanda:7251
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7251
            - CORE_PEER_LOCALMSPID=WakandaGovMSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/WakandaGovMSP/peer0.gov.wakanda/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/WakandaGovMSP/peer0.gov.wakanda/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/WakandaGovMSP/peer0.gov.wakanda/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/WakandaGovMSP/peer0.gov.wakanda/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.gov.wakanda:7351
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.gov.wakanda:7251
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7252
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/WakandaGovMSP/peer0.gov.wakanda
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/WakandaGovMSP/peer0.gov.wakanda:/var/artifacts/production
            - ../artifacts/crypto-config/WakandaGovMSP/peer0.gov.wakanda:/var/artifacts/crypto-config/WakandaGovMSP/peer0.gov.wakanda
        ports:
            - 7251:7251
            - 7253:7253

    peer1.gov.wakanda:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer1.gov.wakanda
        restart: unless-stopped
        environment:
            - CORE_PEER_ID=peer1.gov.wakanda
            - CORE_PEER_ADDRESS=peer1.gov.wakanda:7351
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7351
            - CORE_PEER_LOCALMSPID=WakandaGovMSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/WakandaGovMSP/peer1.gov.wakanda/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/WakandaGovMSP/peer1.gov.wakanda/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/WakandaGovMSP/peer1.gov.wakanda/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/WakandaGovMSP/peer1.gov.wakanda/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.gov.wakanda:7251
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.gov.wakanda:7351
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7352
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/WakandaGovMSP/peer1.gov.wakanda
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/WakandaGovMSP/peer1.gov.wakanda:/var/artifacts/production
            - ../artifacts/crypto-config/WakandaGovMSP/peer1.gov.wakanda:/var/artifacts/crypto-config/WakandaGovMSP/peer1.gov.wakanda
        ports:
            - 7351:7351
            - 7353:7353

    cli:
        extends:
            file: nodebase.yaml
            service: cli-base
        container_name: cli
        restart: unless-stopped
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=peer0.pcch.net:7051
            - CORE_PEER_LOCALMSPID=PccHMSP
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/PccHMSP/peer0.pcch.net/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
        command: sh
        volumes:
            - ../artifacts:/var/artifacts
            - ../scripts/container:/setup
            - ../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
            - .:/config